kind: Service
apiVersion: v1
metadata:
    name: flask-app-service
    namespace: flask-app-ns
spec:
    selector:
        app: flask-app-label
    ports:
        - port: 5000
          targetPort: 5000
          protocol: TCP